package com.wybs.mbti.dal.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuestionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * <p>This field corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * <p>This field corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * <p>This field corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * <p>This field corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected Long offset;

    /**
     * This field was generated by MyBatis Generator.
     * <p>This field corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public QuestionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        offset = null;
        limit = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public void setOffset(Long offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public Long getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public Integer getLimit() {
        return this.limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public QuestionsExample bound(Long offset, Integer limit) {
        this.offset = offset;
        this.limit = limit;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * <p>This class corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("mq.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("mq.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("mq.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("mq.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("mq.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mq.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("mq.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("mq.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("mq.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("mq.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("mq.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mq.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQNoIsNull() {
            addCriterion("mq.q_no is null");
            return (Criteria) this;
        }

        public Criteria andQNoIsNotNull() {
            addCriterion("mq.q_no is not null");
            return (Criteria) this;
        }

        public Criteria andQNoEqualTo(Integer value) {
            addCriterion("mq.q_no =", value, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoNotEqualTo(Integer value) {
            addCriterion("mq.q_no <>", value, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoGreaterThan(Integer value) {
            addCriterion("mq.q_no >", value, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("mq.q_no >=", value, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoLessThan(Integer value) {
            addCriterion("mq.q_no <", value, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoLessThanOrEqualTo(Integer value) {
            addCriterion("mq.q_no <=", value, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoIn(List<Integer> values) {
            addCriterion("mq.q_no in", values, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoNotIn(List<Integer> values) {
            addCriterion("mq.q_no not in", values, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoBetween(Integer value1, Integer value2) {
            addCriterion("mq.q_no between", value1, value2, "qNo");
            return (Criteria) this;
        }

        public Criteria andQNoNotBetween(Integer value1, Integer value2) {
            addCriterion("mq.q_no not between", value1, value2, "qNo");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("mq.title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("mq.title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("mq.title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("mq.title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("mq.title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("mq.title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("mq.title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("mq.title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("mq.title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("mq.title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("mq.title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("mq.title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("mq.title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("mq.title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("mq.code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("mq.code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("mq.code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("mq.code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("mq.code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mq.code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("mq.code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("mq.code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("mq.code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("mq.code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("mq.code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("mq.code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("mq.code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("mq.code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCountCodeIsNull() {
            addCriterion("mq.count_code is null");
            return (Criteria) this;
        }

        public Criteria andCountCodeIsNotNull() {
            addCriterion("mq.count_code is not null");
            return (Criteria) this;
        }

        public Criteria andCountCodeEqualTo(String value) {
            addCriterion("mq.count_code =", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeNotEqualTo(String value) {
            addCriterion("mq.count_code <>", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeGreaterThan(String value) {
            addCriterion("mq.count_code >", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mq.count_code >=", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeLessThan(String value) {
            addCriterion("mq.count_code <", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeLessThanOrEqualTo(String value) {
            addCriterion("mq.count_code <=", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeLike(String value) {
            addCriterion("mq.count_code like", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeNotLike(String value) {
            addCriterion("mq.count_code not like", value, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeIn(List<String> values) {
            addCriterion("mq.count_code in", values, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeNotIn(List<String> values) {
            addCriterion("mq.count_code not in", values, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeBetween(String value1, String value2) {
            addCriterion("mq.count_code between", value1, value2, "countCode");
            return (Criteria) this;
        }

        public Criteria andCountCodeNotBetween(String value1, String value2) {
            addCriterion("mq.count_code not between", value1, value2, "countCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("mq.create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("mq.create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("mq.create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("mq.create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("mq.create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mq.create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("mq.create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("mq.create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("mq.create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("mq.create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("mq.create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("mq.create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * <p>This class corresponds to the database table mt_questions
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * <p>This class corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}