package com.wybs.mbti.dal.model;

import java.util.Date;

/**
 * 表名：mt_description
 * <p>说明：结果描述
 *
 * <p>This class was generated by MyBatis Generator.
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Description {
    /**
     * 字段: mt_description.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * 字段: mt_description.result_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 32
     * <p>说明: 结果类型编码
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String resultCode;

    /**
     * 字段: mt_description.result_type
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 1024
     * <p>说明: 结果类型名称
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String resultType;

    /**
     * 字段: mt_description.url
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 2048
     * <p>说明: 结果详情h5页面url
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String url;

    /**
     * 字段: mt_description.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * 字段: mt_description.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_description.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: mt_description.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param id the value for mt_description.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 字段: mt_description.result_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 32
     * <p>说明: 结果类型编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_description.result_code
     *
     * @mbg.generated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * 字段: mt_description.result_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 32
     * <p>说明: 结果类型编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param resultCode the value for mt_description.result_code
     *
     * @mbg.generated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * 字段: mt_description.result_type
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 1024
     * <p>说明: 结果类型名称
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_description.result_type
     *
     * @mbg.generated
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * 字段: mt_description.result_type
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 1024
     * <p>说明: 结果类型名称
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param resultType the value for mt_description.result_type
     *
     * @mbg.generated
     */
    public void setResultType(String resultType) {
        this.resultType = resultType;
    }

    /**
     * 字段: mt_description.url
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 2048
     * <p>说明: 结果详情h5页面url
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_description.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * 字段: mt_description.url
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 2048
     * <p>说明: 结果详情h5页面url
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param url the value for mt_description.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 字段: mt_description.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_description.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: mt_description.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param createTime the value for mt_description.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Description other = (Description) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getResultCode() == null ? other.getResultCode() == null : this.getResultCode().equals(other.getResultCode()))
            && (this.getResultType() == null ? other.getResultType() == null : this.getResultType().equals(other.getResultType()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getResultCode() == null) ? 0 : getResultCode().hashCode());
        result = prime * result + ((getResultType() == null) ? 0 : getResultType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", resultCode=").append(resultCode);
        sb.append(", resultType=").append(resultType);
        sb.append(", url=").append(url);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}