package com.wybs.mbti.dal.model;

import java.util.Date;

/**
 * 表名：mt_questions
 * <p>说明：测试题目
 *
 * <p>This class was generated by MyBatis Generator.
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Questions {
    /**
     * 字段: mt_questions.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * 字段: mt_questions.q_no
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 问题编号/序号
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Integer qNo;

    /**
     * 字段: mt_questions.title
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 1024
     * <p>说明: 问题描述
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String title;

    /**
     * 字段: mt_questions.code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 属性编码
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String code;

    /**
     * 字段: mt_questions.count_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 计算加分的属性编码
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String countCode;

    /**
     * 字段: mt_questions.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * 字段: mt_questions.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_questions.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: mt_questions.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param id the value for mt_questions.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 字段: mt_questions.q_no
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 问题编号/序号
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_questions.q_no
     *
     * @mbg.generated
     */
    public Integer getqNo() {
        return qNo;
    }

    /**
     * 字段: mt_questions.q_no
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 问题编号/序号
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param qNo the value for mt_questions.q_no
     *
     * @mbg.generated
     */
    public void setqNo(Integer qNo) {
        this.qNo = qNo;
    }

    /**
     * 字段: mt_questions.title
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 1024
     * <p>说明: 问题描述
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_questions.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * 字段: mt_questions.title
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 1024
     * <p>说明: 问题描述
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param title the value for mt_questions.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 字段: mt_questions.code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 属性编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_questions.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * 字段: mt_questions.code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 属性编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param code the value for mt_questions.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 字段: mt_questions.count_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 计算加分的属性编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_questions.count_code
     *
     * @mbg.generated
     */
    public String getCountCode() {
        return countCode;
    }

    /**
     * 字段: mt_questions.count_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 计算加分的属性编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param countCode the value for mt_questions.count_code
     *
     * @mbg.generated
     */
    public void setCountCode(String countCode) {
        this.countCode = countCode;
    }

    /**
     * 字段: mt_questions.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_questions.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: mt_questions.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param createTime the value for mt_questions.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Questions other = (Questions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getqNo() == null ? other.getqNo() == null : this.getqNo().equals(other.getqNo()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCountCode() == null ? other.getCountCode() == null : this.getCountCode().equals(other.getCountCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getqNo() == null) ? 0 : getqNo().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCountCode() == null) ? 0 : getCountCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", qNo=").append(qNo);
        sb.append(", title=").append(title);
        sb.append(", code=").append(code);
        sb.append(", countCode=").append(countCode);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}