package com.wybs.mbti.dal.model;

import java.util.Date;

/**
 * 表名：mt_user_result
 * <p>说明：用户测试结果
 *
 * <p>This class was generated by MyBatis Generator.
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserResult {
    /**
     * 字段: mt_user_result.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * 字段: mt_user_result.uud_id
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 登录用户UUDID
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Integer uudId;

    /**
     * 字段: mt_user_result.is_finish
     * <p>必填: false
     * <p>缺省: 0
     * <p>长度: 10
     * <p>说明: 是否完成测试(0:未完成,1:已完成)
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Integer isFinish;

    /**
     * 字段: mt_user_result.E_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: E属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double eTotal;

    /**
     * 字段: mt_user_result.I_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: I属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double iTotal;

    /**
     * 字段: mt_user_result.S_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: S属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double sTotal;

    /**
     * 字段: mt_user_result.N_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: N属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double nTotal;

    /**
     * 字段: mt_user_result.T_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: T属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double tTotal;

    /**
     * 字段: mt_user_result.F_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: F属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double fTotal;

    /**
     * 字段: mt_user_result.J_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: J属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double jTotal;

    /**
     * 字段: mt_user_result.P_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: P属性答案分累计
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Double pTotal;

    /**
     * 字段: mt_user_result.result_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 用户最终测试结果类型编码
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private String resultCode;

    /**
     * 字段: mt_user_result.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * 字段: mt_user_result.update_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This field was generated by MyBatis Generator.
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * 字段: mt_user_result.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * 字段: mt_user_result.id
     * <p>主键: 自动增长
     * <p>必填: true
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param id the value for mt_user_result.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 字段: mt_user_result.uud_id
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 登录用户UUDID
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.uud_id
     *
     * @mbg.generated
     */
    public Integer getUudId() {
        return uudId;
    }

    /**
     * 字段: mt_user_result.uud_id
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 10
     * <p>说明: 登录用户UUDID
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param uudId the value for mt_user_result.uud_id
     *
     * @mbg.generated
     */
    public void setUudId(Integer uudId) {
        this.uudId = uudId;
    }

    /**
     * 字段: mt_user_result.is_finish
     * <p>必填: false
     * <p>缺省: 0
     * <p>长度: 10
     * <p>说明: 是否完成测试(0:未完成,1:已完成)
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.is_finish
     *
     * @mbg.generated
     */
    public Integer getIsFinish() {
        return isFinish;
    }

    /**
     * 字段: mt_user_result.is_finish
     * <p>必填: false
     * <p>缺省: 0
     * <p>长度: 10
     * <p>说明: 是否完成测试(0:未完成,1:已完成)
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param isFinish the value for mt_user_result.is_finish
     *
     * @mbg.generated
     */
    public void setIsFinish(Integer isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * 字段: mt_user_result.E_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: E属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.E_total
     *
     * @mbg.generated
     */
    public Double geteTotal() {
        return eTotal;
    }

    /**
     * 字段: mt_user_result.E_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: E属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param eTotal the value for mt_user_result.E_total
     *
     * @mbg.generated
     */
    public void seteTotal(Double eTotal) {
        this.eTotal = eTotal;
    }

    /**
     * 字段: mt_user_result.I_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: I属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.I_total
     *
     * @mbg.generated
     */
    public Double getiTotal() {
        return iTotal;
    }

    /**
     * 字段: mt_user_result.I_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: I属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param iTotal the value for mt_user_result.I_total
     *
     * @mbg.generated
     */
    public void setiTotal(Double iTotal) {
        this.iTotal = iTotal;
    }

    /**
     * 字段: mt_user_result.S_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: S属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.S_total
     *
     * @mbg.generated
     */
    public Double getsTotal() {
        return sTotal;
    }

    /**
     * 字段: mt_user_result.S_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: S属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param sTotal the value for mt_user_result.S_total
     *
     * @mbg.generated
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * 字段: mt_user_result.N_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: N属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.N_total
     *
     * @mbg.generated
     */
    public Double getnTotal() {
        return nTotal;
    }

    /**
     * 字段: mt_user_result.N_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: N属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param nTotal the value for mt_user_result.N_total
     *
     * @mbg.generated
     */
    public void setnTotal(Double nTotal) {
        this.nTotal = nTotal;
    }

    /**
     * 字段: mt_user_result.T_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: T属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.T_total
     *
     * @mbg.generated
     */
    public Double gettTotal() {
        return tTotal;
    }

    /**
     * 字段: mt_user_result.T_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: T属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param tTotal the value for mt_user_result.T_total
     *
     * @mbg.generated
     */
    public void settTotal(Double tTotal) {
        this.tTotal = tTotal;
    }

    /**
     * 字段: mt_user_result.F_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: F属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.F_total
     *
     * @mbg.generated
     */
    public Double getfTotal() {
        return fTotal;
    }

    /**
     * 字段: mt_user_result.F_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: F属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param fTotal the value for mt_user_result.F_total
     *
     * @mbg.generated
     */
    public void setfTotal(Double fTotal) {
        this.fTotal = fTotal;
    }

    /**
     * 字段: mt_user_result.J_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: J属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.J_total
     *
     * @mbg.generated
     */
    public Double getjTotal() {
        return jTotal;
    }

    /**
     * 字段: mt_user_result.J_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: J属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param jTotal the value for mt_user_result.J_total
     *
     * @mbg.generated
     */
    public void setjTotal(Double jTotal) {
        this.jTotal = jTotal;
    }

    /**
     * 字段: mt_user_result.P_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: P属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.P_total
     *
     * @mbg.generated
     */
    public Double getpTotal() {
        return pTotal;
    }

    /**
     * 字段: mt_user_result.P_total
     * <p>必填: false
     * <p>缺省: 0.0
     * <p>长度: 11
     * <p>说明: P属性答案分累计
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param pTotal the value for mt_user_result.P_total
     *
     * @mbg.generated
     */
    public void setpTotal(Double pTotal) {
        this.pTotal = pTotal;
    }

    /**
     * 字段: mt_user_result.result_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 用户最终测试结果类型编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.result_code
     *
     * @mbg.generated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * 字段: mt_user_result.result_code
     * <p>必填: false
     * <p>缺省: 
     * <p>长度: 128
     * <p>说明: 用户最终测试结果类型编码
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param resultCode the value for mt_user_result.result_code
     *
     * @mbg.generated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * 字段: mt_user_result.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 字段: mt_user_result.create_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param createTime the value for mt_user_result.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 字段: mt_user_result.update_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @return the value of mt_user_result.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 字段: mt_user_result.update_time
     * <p>必填: true
     * <p>缺省: CURRENT_TIMESTAMP
     * <p>长度: 19
     * <p>说明: 
     *
     * <p>This method was generated by MyBatis Generator.
     *
     * @param updateTime the value for mt_user_result.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserResult other = (UserResult) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUudId() == null ? other.getUudId() == null : this.getUudId().equals(other.getUudId()))
            && (this.getIsFinish() == null ? other.getIsFinish() == null : this.getIsFinish().equals(other.getIsFinish()))
            && (this.geteTotal() == null ? other.geteTotal() == null : this.geteTotal().equals(other.geteTotal()))
            && (this.getiTotal() == null ? other.getiTotal() == null : this.getiTotal().equals(other.getiTotal()))
            && (this.getsTotal() == null ? other.getsTotal() == null : this.getsTotal().equals(other.getsTotal()))
            && (this.getnTotal() == null ? other.getnTotal() == null : this.getnTotal().equals(other.getnTotal()))
            && (this.gettTotal() == null ? other.gettTotal() == null : this.gettTotal().equals(other.gettTotal()))
            && (this.getfTotal() == null ? other.getfTotal() == null : this.getfTotal().equals(other.getfTotal()))
            && (this.getjTotal() == null ? other.getjTotal() == null : this.getjTotal().equals(other.getjTotal()))
            && (this.getpTotal() == null ? other.getpTotal() == null : this.getpTotal().equals(other.getpTotal()))
            && (this.getResultCode() == null ? other.getResultCode() == null : this.getResultCode().equals(other.getResultCode()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUudId() == null) ? 0 : getUudId().hashCode());
        result = prime * result + ((getIsFinish() == null) ? 0 : getIsFinish().hashCode());
        result = prime * result + ((geteTotal() == null) ? 0 : geteTotal().hashCode());
        result = prime * result + ((getiTotal() == null) ? 0 : getiTotal().hashCode());
        result = prime * result + ((getsTotal() == null) ? 0 : getsTotal().hashCode());
        result = prime * result + ((getnTotal() == null) ? 0 : getnTotal().hashCode());
        result = prime * result + ((gettTotal() == null) ? 0 : gettTotal().hashCode());
        result = prime * result + ((getfTotal() == null) ? 0 : getfTotal().hashCode());
        result = prime * result + ((getjTotal() == null) ? 0 : getjTotal().hashCode());
        result = prime * result + ((getpTotal() == null) ? 0 : getpTotal().hashCode());
        result = prime * result + ((getResultCode() == null) ? 0 : getResultCode().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uudId=").append(uudId);
        sb.append(", isFinish=").append(isFinish);
        sb.append(", eTotal=").append(eTotal);
        sb.append(", iTotal=").append(iTotal);
        sb.append(", sTotal=").append(sTotal);
        sb.append(", nTotal=").append(nTotal);
        sb.append(", tTotal=").append(tTotal);
        sb.append(", fTotal=").append(fTotal);
        sb.append(", jTotal=").append(jTotal);
        sb.append(", pTotal=").append(pTotal);
        sb.append(", resultCode=").append(resultCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}