package com.wybs.mbti.dal.mapper;

import com.wybs.mbti.dal.example.DescriptionExample;
import com.wybs.mbti.dal.model.Description;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    long countByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int deleteByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int insert(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int insertSelective(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    Description selectOneByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    List<Description> selectByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    Description selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Description record, @Param("example") DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Description record, @Param("example") DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_description
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Description record);
}