package com.wybs.mbti.dal.mapper;

import com.wybs.mbti.dal.example.QuestionsExample;
import com.wybs.mbti.dal.model.Questions;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    long countByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int deleteByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int insert(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int insertSelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    Questions selectOneByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    List<Questions> selectByExample(QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    Questions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Questions record, @Param("example") QuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_questions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Questions record);
}