package com.wybs.mbti.dal.mapper;

import com.wybs.mbti.dal.example.UserResultExample;
import com.wybs.mbti.dal.model.UserResult;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    long countByExample(UserResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int deleteByExample(UserResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int insert(UserResult record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int insertSelective(UserResult record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    UserResult selectOneByExample(UserResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    List<UserResult> selectByExample(UserResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    UserResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserResult record, @Param("example") UserResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserResult record, @Param("example") UserResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserResult record);

    /**
     * This method was generated by MyBatis Generator.
     * <p>This method corresponds to the database table mt_user_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserResult record);
}